### ISSUE TITLE
TODO before blacklist feature

### ISSUE THREAD

**Issue by mindofmar** [wallet-guard/wallet-guard#3]
**v0.0.4**
Merge & release fix for checking 'contains' (>5 characters) https://github.com/mindofmar/wallet-guard/issues/26 
- [x] fixed in https://github.com/mindofmar/wallet-guard/pull/33
- [x] Release on chrome store

**v0.0.5**
- [ ] Fix 'big tech' issues - Move them to a separate whitelist so that they aren't checked with the normal web3 algo - https://github.com/mindofmar/wallet-guard/issues/21
- [ ] Fix .bit.cc issue https://github.com/mindofmar/wallet-guard/pull/37
- [ ] Fix HTTPS Everywhere issue https://github.com/mindofmar/wallet-guard/issues/39
- [ ] Release on chrome store

**v0.0.6** (assuming no other issues pop up)
- [ ] Blacklist/admin dashboard feature
